# Generated by Django 5.2.11 on 2026-02-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='created_at',
        ),
        migrations.AddField(
            model_name='question',
            name='json_upload',
            field=models.FileField(blank=True, help_text='Toplu soru eklemek için JSON dosyası yükleyin', null=True, upload_to='question_imports/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation_tr',
            field=models.TextField(blank=True, default=''),
        ),
    ]
