# Generated by Django 5.1.6 on 2025-03-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_cruduser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cruduser',
            name='last_login_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
