# Generated by Django 5.1.7 on 2025-03-31 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_cruduser_last_login_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cruduser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("team_lead", "Team Lead"),
                    ("member", "Member"),
                    ("viewer", "Viewer"),
                ],
                default="viewer",
                max_length=20,
            ),
        ),
    ]
